### ISSUE TITLE
IORING_FEAT_FAST_POLL question

### ISSUE THREAD

**Issue by romange** [frevib/io_uring-echo-server#5]
Hi,

I do not see anything in your code that does something differently. what IORING_FEAT_FAST_POLL does and where exactly you use it? (besides testing it in the features)

**Comment by frevib** [comment]
Hi Roman, have a look at this brach: https://github.com/frevib/io_uring-echo-server/tree/io-uring-feat-fast-poll

With IORING_FEAT_FAST_POLL you don’t have to poll a socket for ready data. So you can just call a `recv` (`io_uring_prep_recv`) on a socket and the moment there’s data ready it will complete and return as a`cqe` on your ring. Because you don’t have to poll, you save a sys call. This can result in much better performance: https://github.com/frevib/io_uring-echo-server/blob/io-uring-feat-fast-poll/benchmarks/benchmarks.md

**Comment by romange** [comment]
Thanks for the explanation. Will wait untill 5.7 is out to test it!

**Comment by Sherlock-Holo** [comment]
@frevib That makes me confuse, when the fast poll doesn't exist in old kernel, I still can readv the tcp socket directly through io_uring, so what fast poll actually do in the new kernel？

**Comment by eecheng87** [comment]
Hi, @frevib 
In [io_uring-echo-server example](https://github.com/frevib/io_uring-echo-server/blob/io-uring-feat-fast-poll/io_uring_echo_server.c), I only saw you check whether `IORING_FEAT_FAST_POLL` is supported.

Don't we set the flag before `io_uring_queue_init_params`? Is this feature is default?

Thanks in advance.

**Comment by frevib** [comment]
Hi,

This echo server was built a two years ago when io_uring was not very well known and didn’t have many features. So maybe things have changed and we need so set `io_uring_queue_init_params` like you say, but I don’t know.
